### ISSUE TITLE
hastec hangs

### ISSUE THREAD

**Issue by DanielCollins** [valderman/haste-compiler#240]
hastec --opt-whole-program --opt-minify script.hs

With either of those flags, returns within a few seconds and produces a working program, but with both of those flags, hastec appears to hang. script.hs looks like this:

import Haste

main :: IO ()
main = do
  Just element <- elemById "element"
  prop <- getProp element "prop"
  print prop

hastec --version
0.4.2

**Comment by DanielCollins** [comment]
Thank you @concavelenz 

closure closed their issue jan 6th. i haven't tested it with hastec yet and the last closure release is still December 15, 2014. 

Does haste bundle closure or rely on system closure or does it install through cabal or something else?

**Comment by valderman** [comment]
`haste-boot` pulls in closure from http://valderman.github.io/haste-libs/. It used to download it directly from Google, but the URL would change every x months, so I'm mirroring a reasonably current release to avoid unnecessary breakage. I'll update the mirror as soon as a version containing the fix is released, after that it will be possible to update Haste's default closure.jar by doing `haste-boot --force --no-libs --no-populate-setup-exe-cache` if you installed via cabal. Binary packages will need to be updated with a new closure, so there'll be a new point release by then, probably.

**Comment by DanielCollins** [comment]
Just to let you know, there's been a new closure release. Haven't tested it.

**Comment by valderman** [comment]
It solves the problem, at least for this test case. Updated haste-libs, so running haste-boot from now on should get the updated version.
