### ISSUE TITLE
Weird bugs without --ddisable-js-opts

### ISSUE THREAD

**Issue by kranich** [valderman/haste-compiler#292]
I experience weird bugs due to optimization as in #289.

It would be great if we had flags to disable optimizations individually. This would also make debugging much easier.

**Comment by valderman** [comment]
On the 0.6 branch, it's now possible to individually enable/disable most optimizations. The ones that are not individually controllable are simple, rock-stable prettifications that have been in the code base since forever. See the [manual page](https://github.com/valderman/haste-compiler/blob/master/doc/hastec.1.md) for more information.
