### ISSUE TITLE
`withWebSocket` does not report why errors occur, nor does it report when socket closed

### ISSUE THREAD

**Issue by TazeTSchnitzel** [valderman/haste-compiler#322]
https://github.com/valderman/haste-compiler/blob/master/libraries/haste-lib/src/Haste/WebSockets.hs#L62

This makes debugging a pain, because you know an error's occurred, but not *which* error.

(might implement this later if I can - how would the new function be named?)

**Comment by TazeTSchnitzel** [comment]
Actually, there's a question. What's your policy on backwards-compatibility? Would it be acceptable to change the existing function signature?

**Comment by valderman** [comment]
As a rule, I'm trying to preserve backwards compatibility as much as possible. (Hence the counter-intuitive argument order of `addChild` and friends.) However, with 0.5 there's going to be some major breakage anyway from the GHC 7.10 transition, updated event API and other assorted "OK, this thing sucks, let's make it nicer while we're breaking stuff anyway" fixes. As such, pretty much any breakage which makes things nicer or more useful is OK for 0.5.

The important thing is that any breakage is very visible at compile time. Changes that require new type signatures are the best ones since they're pretty hard to miss. For changes to broken/annoying/inconsistent semantics that _don't_ require a new type signature, it's probably best to introduce a new function with the new semantics and slap a deprecation warning on the old one.

**Comment by valderman** [comment]
The `onerror` event actually contains no error information at all. However, the `onclose` event does. The new WebSockets API provides a way to get at this information.
