### ISSUE TITLE
`hastec` can't see modules installed by `haste-cabal`

### ISSUE THREAD

**Issue by TazeTSchnitzel** [valderman/haste-compiler#326]
I suspect I'm doing something wrong here, but I don't know what.

I installed the `containers` package with haste-cabal:

```
haste-cabal install containers
```

and I compiled my code:

```
hastec Client.hs
```

But it's unable to find [the module I need from `containers`](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/containers/Data-Map-Strict.html):

```
World.hs:9:8:
    Could not find module ‘Data.Map.Strict’
    Use -v to see a list of the files searched for.
```

`World.hs` is a module I wrote, used by the `Client` module.

**Comment by TazeTSchnitzel** [comment]
At this point I might end up abandoning Haste, much as it pains me.

**Comment by valderman** [comment]
`Data.Map.Strict` appears in `containers` with version 0.5.6. `haste-lib` specifically depends on any version of containers *lower* than that, so this is expected behavior.

However, now that the reason (#282) for this slightly outdated restriction is gone (due to recent work on performance and memory use), this restriction should go away (hence 9231184 getting pushed just now).

Sorry for taking long to respond to bug reports. I'm currently on vacation with a rather sporadic Internet presence.

**Comment by TazeTSchnitzel** [comment]
Ahh, that explains it. I hadn't considered that it was a versions thing, that's pretty bad on my part.

Don't worry about the bug reports delay, I'm unreasonably impatient.
