### ISSUE TITLE
Error running Haste-boot on GHCJS El Capitan.

### ISSUE THREAD

**Issue by MaiaVictor** [valderman/haste-compiler#363]
I installed the binary from the site.

    Vs-MacBook:tests v$ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.2
    Vs-MacBook:tests v$ haste-boot
    Downloading haste-cabal from GitHub
    Downloading Google Closure compiler...
    Downloading base libs from GitHub
    Reading package info from "libraries/rts.pkg" ... done.
    Warning: The package list for 'hackage.haskell.org' is 46 days old.
    Run 'cabal update' to get the latest list of available packages.
    Warning: Topdown solver is deprecated
    Resolving dependencies...
    Configuring ghc-prim-0.4.0.0...
    Building ghc-prim-0.4.0.0...
    Installed ghc-prim-0.4.0.0
    Reading package info from "ghc-prim-0.4.0.0-osx.conf" ... done.
    ghc-prim-0.4.0.0: Warning: library-dirs: /Users/v/.haste/x86_64-darwin-haste-0.5.3-ghc-7.10.2/ghc-prim-0.4.0.0 doesn't exist or isn't a directory
    ghc-prim-0.4.0.0: import-dirs: /Users/v/.haste/x86_64-darwin-haste-0.5.3-ghc-7.10.2/ghc-prim-0.4.0.0 doesn't exist or isn't a directory (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/CString.hi","GHC/CString.p_hi","GHC/CString.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/Classes.hi","GHC/Classes.p_hi","GHC/Classes.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/Debug.hi","GHC/Debug.p_hi","GHC/Debug.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/IntWord64.hi","GHC/IntWord64.p_hi","GHC/IntWord64.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/Magic.hi","GHC/Magic.p_hi","GHC/Magic.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/PrimopWrappers.hi","GHC/PrimopWrappers.p_hi","GHC/PrimopWrappers.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/Tuple.hi","GHC/Tuple.p_hi","GHC/Tuple.dyn_hi"] (use --force to override)
    ghc-prim-0.4.0.0: cannot find any of ["GHC/Types.hi","GHC/Types.p_hi","GHC/Types.dyn_hi"] (use --force to override)
    Command '/Users/v/.cabal/bin/haste-pkg' failed with error  code 1

**Comment by valderman** [comment]
Running `haste-boot` should never be necessary with the binaries; in fact, the command should not even be present. What is the output of `which haste-boot`?

**Comment by MaiaVictor** [comment]
I was using a version installed with cabal.

**Comment by tobi512** [comment]
@valderman I'm running into the same error and found the cause for the missing ghc-prim if you're interested:
Internally when running "haste-boot" some files are downloaded into a folder, which should not be created, because its a duplicate then. So this seems to be a simple path-problem, i'll attach a screenshot from Finder, which shows it.
<img width="863" alt="haste-boot-issue" src="https://cloud.githubusercontent.com/assets/2721729/13061649/5fffa420-d439-11e5-9851-7904b6f0b349.png">
`/Users/v/.haste/x86_64-darwin-haste-0.5.4-ghc-7.10.2/ghc-prim-0.4.0.0` obviously doesn't exist (since its inside another `x86_64-osx-haste-0.5.4-ghc-7.10.2`-folder and the whole thing fails...

So "Running `haste-boot` should never be necessary with the binaries;" means just `cabal install haste-compiler` is enough and `hastec` works then?

Thanks in advance!

**Comment by valderman** [comment]
No, if you install from source (i.e. using cabal, either from GitHub or from Hackage) you always need `haste-boot`. However, the binaries available from [haste-lang.org](http://haste-lang.org/downloads/) are pre-booted and should work right out of the box, no booting required.

Regarding the error, it seems like yet another case of GHC behaving completely unpredictably WRT paths on OSX. I don't have a mac available so I'm not sure when I'll be able to sort this out, unfortunately. Patches to fix this and other OS-specific issues are particularly welcome.

**Comment by tobi512** [comment]
Thanks for your quick reply! @valderman 
I didn't try to use `hastec` right after binary install, since the documentation on the main github-page says: 

Or, you can install the latest stable version from Hackage:
$ cabal install haste-compiler
$ haste-boot

I tried to compile from source after i got into the `haste-boot` errors, so this might be the cause for the necessary booting then. 
However, i just successfully booted it a couple mins ago by copying and inserting the `ghc-prim-0.4.0.0`-folder to the right place at the right time during `haste-boot` (dirty workaround, but i needed a working version asap). For me this looks like a simple path-problems in one of the scripts, no?!
I'll try to translate some Haskell code to JavaScript for a Webapp now, thanks again! :smiley:
